dist: trusty
language: node_js
node_js:
  - "6"
services:
  - postgresql

before_script:
  - psql -c 'create database docman_test;' -U postgres
script:
- npm test
# Run selenium tests
- npm run test:e2e


after_success:
  - npm run coveralls
