import keyMirror from 'keymirror';

export default keyMirror({
  CREATE_USER_SUCCESS: null,
  LOGIN_USER_SUCCESS: null,
  LOGIN_USER_FAILURE: null,
  SET_CURRENT_USER: null,

  SEARCH_ALLUSERS_SUCCESS: null,
  SEARCH_ALLDOCUMENTS_SUCCESS: null,

  GET_USERS_SUCCESS: null,
  GET_AUTH_USER_SUCCESS: null,
  LOAD_USERS_SUCCESS: null,
  SET_SELECTED_USER: null,
  DISPLAY_SELECT_USER: null,
  UPDATE_USER_SUCCESS: null,
  DELETE_SELECTED_USER: null,

  ADD_FLASH_MESSAGE: null,
  DELETE_FLASH_MESSAGE: null,

  LOAD_DOCUMENT_SUCCESS: null,
  CREATE_DOCUMENT_SUCCESS: null,
  SET_CURRENT_DOCUMENT: null,
  DELETE_CURRENT_DOCUMENT: null,
  DISPLAY_SELECTED_DOCUMENT: null,

  LOAD_ROLE_SUCCESS: null,
  SET_CURRENT_ROLE: null,
  DELETE_CURRENT_ROLE: null
});
