export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE ';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const DISPLAY_SELECT_USER = 'DISPLAY_SELECT_USER';
export const DELETE_SELECTED_USER = 'DELETE_SELECTED_USER';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOAD_DOCUMENT_SUCCESS = 'LOAD_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const SET_CURRENT_DOCUMENT = 'SET_CURRENT_DOCUMENT';
export const DELETE_CURRENT_DOCUMENT = 'DELETE_CURRENT_DOCUMENT';

export const LOAD_ROLE_SUCCESS = 'LOAD_ROLE_SUCCESS';
export const SET_CURRENT_ROLE = 'SET_CURRENT_ROLE';
export const DELETE_CURRENT_ROLE = 'DELETE_CURRENT_ROLE';
